apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: <acr_login_server>/mediawiki
        ports:
        - containerPort: 80
