# Using the official MediaWiki image from Docker Hub
FROM mediawiki

# Set environment variables
ENV MEDIAWIKI_DB_TYPE=mysql \
    MEDIAWIKI_DB_HOST=db \
    MEDIAWIKI_DB_PORT=3306 \
    MEDIAWIKI_DB_NAME=my_wiki \
    MEDIAWIKI_DB_USER=root \
    MEDIAWIKI_DB_PASSWORD=password

# Expose port 80 for HTTP access
EXPOSE 80

# Start MediaWiki
CMD ["apache2-foreground"]
